config/routes.rb
Rails.application.routes.draw do


  get 'contacts/new'
  # devise
  devise_for :users, :controller => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_for :admins, :controller => {
    :sessions => 'admins/sessions'
  }


  # common
  root 'products#index'
  get '/top' => 'users#top', as: 'top'
  get '/search' => 'products#index', as: 'search'
  resources :users, only: [:show, :edit, :update]
  resource :addresses, only: [:create, :update, :destroy]
  resources :carts, only: [:index, :show, :edit, :update]
  resources :products, only: [:show] do
    resources :carts, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]	
    resource :favorites, only: [:create, :destroy] 
  end
  resources :orders, only: [:new, :create, :index]
  resources :ordered_products, only: [:new, :create, :show]
  resources :contacts, only: [:new, :create]



  # admin
  namespace :admins do
    resources :users, only: [:index]
    resources :products, only: [:new, :create, :edit, :update, :destroy]
    resources :contacts, only: [:index, :show, :edit, :update, :destroy] do
      resource :contact_replies, only: [:create]
    end
    resources :genres
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # attachment 
  attachment :profile_image

  # association
  has_many :addresses, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy



end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
  end

end

app/controllers/users/base.rb
class User::Base < ApplicationController
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
     self.addresses.build
   end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def top
  end

  def show
    @user = User.find(params[:id])
    @ad = current_user.addresses.build
    @carts = Cart.where(user_id: current_user.id)
    @fav = Favorite.where(user_id: @user.id)
    @order = Order.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to user_path(user.id)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_lana, :gender, :birth, :profile_image)
  end


end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for @user do |user| %>
  <%= user.attachment_field :profile_image %>
  <p>姓</p>
  <%= user.text_field :first_name %>
  <p>名</p>
  <%= user.text_field :last_name %>
  <p>セイ</p>
  <%= user.text_field :first_name_kana %>
  <p>メイ</p>
  <%= user.text_field :last_name_lana %>
  <%= user.submit 'submit' %>

<% end %>

app/views/users/show.html.erb
<div class="inner">
  <div class="inner__show">
    <div class="user__top">
      <div class="user__top--left">
        <p class="user__left--profile-image">
           <%= attachment_image_tag @user, :profile_image %>
        </p> 
      </div>
      <div class="user_top--right">
        <p class="user__right--user-name"> 
          <%= @user.first_name %><%= @user.last_name %>
        </p>
        <p class="user__right--user-name-kana"> 
          <%= @user.first_name_kana %><%= @user.last_name_lana %>
        </p>
        <p class="user__right--gender">
          <%= @user.gender %>
        </p> 
        <p class="user__right--birth">
          <%= @user.birth %>
        </p> 
        <p class="user__right--email">
          <%= @user.email %>
        </p> 
        <p><%= link_to '編集', edit_user_path(current_user.id) %></p>
        <p><%= link_to '退会', user_registration_path, method: :destros %></p>
      </div>
    </div>
  </div><!-- user__top -->
  <ul class="user__tabs">
    <li class="user__tab is_selected">
      Carts
    </li>
    <li class="user__tab">
      Ordered
    </li>
    <li class="user__tab">
      Addresses
    </li>
    <li class="user__tab">
      Favorites
    </li>
  </ul><!-- user__tab -->

  <div id="cart" class="user__cart user__content is_active">
<% @carts.each do |c| %>
  <%= c.product.album_name %>
<% end %>
  </div>
  <div id="order" class="user__order user__content">
<% @order.each do |o| %>
  <%= o.created_at %>
  <labeL>送付先i：<%= o.address.sending_address %></labeL>
  <%= o.order_status %>
  <% o.ordered_products.each do |op| %>
    <%= op.genre.genre_name %>
    <%= op.product_name %>
    <%= op.artist_name %>
    <%= attachment_image_tag op, :jacket_image %>
    <%= op.price %>
    <%= op.quantity %>
  <% end %>
<% end %>
  </div>
  <div id="address" class="user__address user__content">
    <div class="address__left">
      <%= form_for @ad, url: addresses_path, method: :post  do |ad| %>
        <p class="form__adress--new">
          <p class=="form__label">送付先住所</p>
          <%= ad.text_field :sending_address %>
        </p>
        <p class="form__adress--new">
          <p class=="form__label">電話番号</p>
          <%= ad.text_field :phone %>
        </p>
        <p class="form__adress--new">
          <p class=="form__label">郵便番号</p>
          <%= ad.text_field :postal_code %>
        </p>
        <p class="form__adress--new">
          <p class=="form__label">受取人氏名（漢字）</p>
          <%= ad.text_field :receiver_name %>
        </p>
        <p class="form__adress--new">
          <p class=="form__label">受取人（カナ）</p>
          <%= ad.text_field :receiver_name_kana %>
        </p>
        <p class="form__adress--new">
          <%= ad.submit 'Add address' %>
        </p>
      <% end %>
    </div><!-- address__left -->
    <div class="address__right">
      <% @user.addresses.each do |ad| %>
        <div class="address__items">
          <p class="address__address">
            <p>
              送付先住所
            </p>
            <%= ad.sending_address %>
          </p>
          <p class="addrss__address">
            <p>
              電話番号
            </p>
            <%= ad.phone %>
          </p>
          <p class="addrss__address">
            <p>
              郵便番号
            </p>
            <%= ad.postal_code %>
          </p>
          <p class="addrss__address">
            <p>
              受取人氏名
            </p>
            <%= ad.receiver_name %>
          </p>
          <p class="addrss__address">
            <p>
              受取人シメイ
            </p>
            <%= ad.receiver_name_kana %>
          </p>
        </div>
      <% end %>
    </div><!--  address__right-->
  </div>
  <div id="fav" class="user__fav user__content">
<% @fav.each do |f| %>
  <%= f.product.album_name %>
  <%= f.product.artist_name %>
  <%= f.product.price %>
<% end %>
  </div>
</div>

app/views/users/top.html.erb
<div class="inner">
  <div class="inner__top">
    <div class="top__top">
      Welcome to CD samurai,
    </div>
    <div class="top__middle">
      <div class="top__middle--top">
      We all expect you’ll take a great CD trip in our site.<br>
      Hopefully, get some cd’s you prefer.
      </div>
      <div class="top__middle--bottom">
        We are here to help you meet with brilliant songs.
      </div>
    </div>
    <div class="top__bottom">
      <p class="top__bottom--top">Sincerely,</p>
      <p class="top__bottom--bottom">- Steve Teyoung</p>
    </div>
  </div>
</div>