config/routes.rb
Rails.application.routes.draw do


  get 'contacts/new'
  # devise
  devise_for :users, :controller => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_for :admins, :controller => {
    :sessions => 'admins/sessions'
  }


  # common
  root 'products#index'
  get '/top' => 'users#top', as: 'top'
  get '/search' => 'products#index', as: 'search'
  resources :users, only: [:show, :edit, :update]
  resource :addresses, only: [:create, :update, :destroy]
  resources :carts, only: [:index, :show, :edit, :update]
  resources :products, only: [:show] do
    resources :carts, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]	
    resource :favorites, only: [:create, :destroy] 
  end
  resources :orders, only: [:new, :create, :index]
  resources :ordered_products, only: [:new, :create, :show]
  resources :contacts, only: [:new, :create]



  # admin
  namespace :admins do
    resources :users, only: [:index]
    resources :products, only: [:new, :create, :edit, :update, :destroy]
    resources :contacts, only: [:index, :show, :edit, :update, :destroy] do
      resource :contact_replies, only: [:create]
    end
    resources :genres
  end


end

app/models/address.rb
class Address < ApplicationRecord

  has_many :orders

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/comment.rb
class Comment < ApplicationRecord

  # association
  belongs_to :user

end

app/models/contact.rb
class Contact < ApplicationRecord

  has_many :contact_replies

end

app/models/contact_reply.rb
class ContactReply < ApplicationRecord
  
  belongs_to :contact

end

app/models/disc.rb
class Disc < ApplicationRecord
  # association
  belongs_to :product
  has_many :songs

  # cocoon
  accepts_nested_attributes_for :songs, allow_destroy: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  # association
  belongs_to :product

end

app/models/genre.rb
class Genre < ApplicationRecord

  # association
  has_many :products

  # cocoon

end

app/models/order.rb
class Order < ApplicationRecord

  # association
  has_many :ordered_products
  belongs_to :address

  # attachment
  attachment :jacket_image

end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  
  # association
  belongs_to :order
  belongs_to :genre

  # attachment
  attachment :jacket_image

end

app/models/product.rb
class Product < ApplicationRecord

  # attachment
  attachment :jacket_image
  
  # association
  has_many :discs, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :genre

  # cocoon
  accepts_nested_attributes_for :discs , allow_destroy: true

  # validates
  validates :album_name , presence: true 
  validates :jacket_image , presence: true 
  validates :price , presence: true 
  validates :stock , presence: true 
  validates :sales_status , presence: true 
  validates :label , presence: true 

  # functions
  def fav_by?(user_id)
    favorites.where(user_id: user_id).exists?
  end

  def self.pro_rank
    Product.find(Favorite.group(:product_id).order('count(product_id) DESC').limit(5).pluck(:product_id))
  end

end

app/models/song.rb
class Song < ApplicationRecord
  
  # association
  belongs_to :disc

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # attachment 
  attachment :profile_image

  # association
  has_many :addresses, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy



end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yayoiken</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header__logo wh">CD samurai</div>
      <div class="header__line wh">|</div>
      <nav class="header__nav">
        <ul class="header__lists wh">
          <% if user_signed_in? %> <!-- ユーザーサインイン時 -->
            <li class="header__list">
              <%= link_to 'Home', root_path %>
            </li>
            <li class="header__list">
              <%= link_to 'MyPage', user_path(current_user) %>
            </li>
            <li class="header__list">
              <%= link_to 'Cart', carts_path %>
            </li>
            <li class="header__list">
              <%= link_to 'Contact', new_contact_path %>
            </li>
            <li class="header__list">
              <%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
            </li>
          <% elsif admin_signed_in? %> <!-- 管理者サインイン時 -->
            <li class="header__list">
              <%= link_to 'Home', root_path %>
            </li>
            <li class="header__list">
              <%= link_to 'Users', admins_users_path %>
            </li>
            <li class="header__list">
              <%= link_to 'Product', new_admins_product_path %>
            </li>
            <li class="header__list">
              <%= link_to 'Genre', new_admins_genre_path %>
            </li>
            <li class="header__list">
              <%= link_to 'Contact', admins_contacts_path %>
            </li>
            <li class="header__list">
              <%= link_to 'LogOut', destroy_admin_session_path, method: :delete %>
            </li>
          <% else %> <!-- 非ログイン時 -->
            <li class="header__list">
              <%= link_to 'Top', top_path %>
            </li>
            <li class="header__list">
              <%= link_to 'Home', root_path %>
            </li>
            <li class="header__list">
              <%= link_to 'LogIn', new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </nav>
      <div class="search">
        <!-- search form -->
      </div>
    </header>
    <div class="wrapper">
      <%= yield %>
    </div>
    <footer>
      ©︎SteveHong, Inc. All rights reserved.
    </footer>
  </body>
</html>