config/routes.rb
Rails.application.routes.draw do


  get 'contacts/new'
  # devise
  devise_for :users, :controller => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_for :admins, :controller => {
    :sessions => 'admins/sessions'
  }


  # common
  root 'products#index'
  get '/top' => 'users#top', as: 'top'
  get '/search' => 'products#index', as: 'search'
  resources :users, only: [:show, :edit, :update]
  resource :addresses, only: [:create, :update, :destroy]
  resources :carts, only: [:index, :show, :edit, :update]
  resources :products, only: [:show] do
    resources :carts, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy]	
    resource :favorites, only: [:create, :destroy] 
  end
  resources :orders, only: [:new, :create, :index]
  resources :ordered_products, only: [:new, :create, :show]
  resources :contacts, only: [:new, :create]



  # admin
  namespace :admins do
    resources :users, only: [:index]
    resources :products, only: [:new, :create, :edit, :update, :destroy]
    resources :contacts, only: [:index, :show, :edit, :update, :destroy] do
      resource :contact_replies, only: [:create]
    end
    resources :genres
  end


end

app/models/address.rb
class Address < ApplicationRecord

  has_many :orders

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/comment.rb
class Comment < ApplicationRecord

  # association
  belongs_to :user

end

app/models/contact.rb
class Contact < ApplicationRecord

  has_many :contact_replies

end

app/models/contact_reply.rb
class ContactReply < ApplicationRecord
  
  belongs_to :contact

end

app/models/disc.rb
class Disc < ApplicationRecord
  # association
  belongs_to :product
  has_many :songs

  # cocoon
  accepts_nested_attributes_for :songs, allow_destroy: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  # association
  belongs_to :product

end

app/models/genre.rb
class Genre < ApplicationRecord

  # association
  has_many :products

  # cocoon

end

app/models/order.rb
class Order < ApplicationRecord

  # association
  has_many :ordered_products
  belongs_to :address

  # attachment
  attachment :jacket_image

end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  
  # association
  belongs_to :order
  belongs_to :genre

  # attachment
  attachment :jacket_image

end

app/models/product.rb
class Product < ApplicationRecord

  # attachment
  attachment :jacket_image
  
  # association
  has_many :discs, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :genre

  # cocoon
  accepts_nested_attributes_for :discs , allow_destroy: true

  # validates
  validates :album_name , presence: true 
  validates :jacket_image , presence: true 
  validates :price , presence: true 
  validates :stock , presence: true 
  validates :sales_status , presence: true 
  validates :label , presence: true 

  # functions
  def fav_by?(user_id)
    favorites.where(user_id: user_id).exists?
  end

  def self.pro_rank
    Product.find(Favorite.group(:product_id).order('count(product_id) DESC').limit(5).pluck(:product_id))
  end

end

app/models/song.rb
class Song < ApplicationRecord
  
  # association
  belongs_to :disc

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # attachment 
  attachment :profile_image

  # association
  has_many :addresses, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy



end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController

  def new
    @product = Product.new
    disc = @product.discs.build # disc
    disc.songs.build # song
  end

  def create
    @product = Product.new(product_params)
    # song_orderのロジックがわからないのでとりま応急措置で1を代入 
    @product.discs.each do |d| d.songs.each do |s| s.song_order = 1 end end
    if @product.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to root_path
  end

  private
  def product_params
    params.require(:product).permit(:album_name, :artist_name, :label, :price, :stock, :sales_status, :jacket_image, :genre_id, discs_attributes: [:id, :disc_name, :_destroy, songs_attributes: [:id, :song_name, :song_order, :_destroy]])
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @rank = Product.pro_rank
    @search = Product.ransack(params[:q])
    @result = @search.result
  end

  def show
    @product = Product.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(product_id: @product.id).order('created_at DESC')
  end

  def new
    @product = Product.new
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_genre_fields.html.erb
<div class="nested-fields">
  <%=  f.texr_field :genre%>
</div>

app/views/products/index.html.erb
<%= search_form_for @search, url: search_path  do |f| %>
  <div class="form-group">
    <%= f.text_field :album_name, class: "form-control" %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>
<% @result.each do |r| %>
  <%= r.album_name %>
<% end %>

<div class="inner">
  <div class="inner__index">
    <div class="index__product">
<!-- プロダクト　ループ処理 -->
      <div class="product__all">
        <% @products.each do |p| %>
          <div class="product__wrapper">
            <%= link_to product_path(p.id) do %>
              <div class="product__image"><%= attachment_image_tag p, :jacket_image  %></div>
              <div class="product__album-name"><%= p.album_name %></div>
              <div class="product__artist-name"><%= p.artist_name %></div>
            <% end %>
<!-- いいね機能 -->
            <% if p.fav_by?(current_user) %>
              <%= link_to product_favorites_path(p.id), method: :delete do %>
                <span class="fav fav__active">❤️</span><i class="fa fa-heart"></i>
              <% end %>
            <% else %>
              <%= link_to product_favorites_path(p.id), method: :post do %>
                <span class="fav fav__deactive">♡</span><i class="fa fa-heart-o"></i>
              <% end %>
            <% end %>
          </div><!-- product__wrapper -->
        <% end %>
        </div><!-- product__all -->

<!-- ランキング機能 -->
      <h1>Ranking this week</h1>
      <div class="rank__all">
      <% @rank.each.with_index(1) do |rank, i| %>
        <div class="rank__wrapper">
        <p class="rank__num"><%= i %></p>
        <p class="rank__image"><%= attachment_image_tag rank, :jacket_image %></p>
        <p class="rank__album-name"><%= rank.album_name %></p>
        <p class=="rank__artist-name"><%= rank.artist_name %></p>
        <p class="rank__fav-count"><%= rank.favorites.count %>いいね</p>
        <% if rank.fav_by?(current_user) %>
          <%= link_to product_favorites_path(rank.id), method: :delete do %>
            いいねしてます<i class="fa fa-heart"></i>
          <% end %>
        <% else %>
          <%= link_to product_favorites_path(rank.id), method: :post do %>
            いいねしてません<i class="fa fa-heart-o"></i>
          <% end %>
        <% end %>
        </div><!-- rank__wrapper -->
      <% end %>
      </div><!-- rank__all -->
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="inner">
<div class="inner__show">
<div class="product__wrapper">
<div class="product__left">
<div class="product__left--jacket-image">
<div class="product__right">
<div class="inner">
<div class="inner">
<div class="inner">

<%= attachment_image_tag @product, :jacket_image %>
<%= @product.album_name %>
<%= @product.price %>
<%= @product.label %>
<%= @product.artist_name %>
<% if @product.stock != 0 %>
  <%= @product.stock %>
<% else %>
  <p>売り切れ</p>
<% end %>
<%= @product.genre.genre_name %>
<% if @product.sales_status == true %>
  <p>On sale</p>
<% else %>
  <p>Out of sale</p>
<% end %>
<% @product.discs.each do |disc| %>
  <%= disc.disc_name %>
  <% disc.songs.each do |song| %>
    <%= song.song_name %>
  <% end %>
<% end %>
<% if current_admin %>
  <%= link_to 'Delete album', admins_product_path, method: :delete %>
<% end %>
<% if current_user %>
  <%= link_to 'Add cart', product_carts_path(@product.id), method: :post %>
<% end %>

<%= form_with model: @comment, url: product_comments_path(@product.id), method: :post,  id:'form__comment' do |c| %>
  <%= c.text_area :comment, class:"field__text field__form input__comment" %>
  <%= c.submit 'コメント' %>
<% end %>

<div class="inner__comment">
<% @comments.each do |comment| %>
  <%= comment.comment %>
<% end %>
</div>